db:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

web:
  restart: always
  build: ./olyke
  links:
    - db
  environment:
    - OLYKE_SECRET
    - OLYKE_SUPER_PASS
    - AWS_OLYKE_BUCKET_NAME
    - AWS_OLYKE_ACCESS_KEY
    - AWS_OLYKE_SECRET_KEY
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  command: /usr/local/bin/gunicorn olyke.wsgi:application -w 2 -b :8000 

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: true
